# Generated by Django 5.2.2 on 2025-06-07 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('1', 'Alta'), ('2', 'Média'), ('3', 'Baixa')], default='2', max_length=1),
        ),
    ]
